#!/usr/bin/env node
// Export .agent-team/team.json with agent-team-creator and install the role
// files into each harness's agent directory. Only files for roster roles are
// written; any other file in a target directory is left alone. Each target
// keeps a marker (.team-agents.json) of the roles it received, so a role
// dropped from the roster is removed (or, with --check, reported).
//
//   node scripts/agent-team/install-exports.mjs           # export + install
//   node scripts/agent-team/install-exports.mjs --check   # export to temp, exit 1 on drift
//
// agent-team-creator is located via $AGENT_TEAM_CREATOR or ~/.claude/skills (see build-manifest.mjs).
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { creatorCli } from "./build-manifest.mjs";

/** Where each target's exporter writes a role file, and where the harness reads it. */
export const TARGETS = {
  claude: { exported: (id) => `.claude/agents/${id}.md`, installed: (id) => `.claude/agents/${id}.md`, dir: ".claude/agents" },
  codex: { exported: (id) => `.codex/agents/${id}.toml`, installed: (id) => `.codex/agents/${id}.toml`, dir: ".codex/agents" },
  opencode: { exported: (id) => `.opencode/agents/${id}.md`, installed: (id) => `.opencode/agents/${id}.md`, dir: ".opencode/agents" },
  kimi: { exported: (id) => `.kimi-code/agents/${id}.md`, installed: (id) => `.kimi-code/agents/${id}.md`, dir: ".kimi-code/agents" },
  // ATH-D-003: MiniMax agents live in the project's .minimax (run mcode with MINIMAX_DATA_DIR=.minimax).
  minimax: { exported: (id) => `agents/${id}/agent.md`, installed: (id) => `.minimax/agents/${id}/agent.md`, dir: ".minimax/agents" },
};
export const MARKER = ".team-agents.json";
export const CODEX_CONFIG = ".codex/config.toml";

/**
 * Codex (0.154) does not auto-discover .codex/agents/*.toml; each agent is
 * registered under [agents.<id>] with a config_file relative to .codex/.
 * Project config applies only once the operator trusts the project in Codex.
 */
export const CODEX_BEGIN = "# >>> agent-team roles (generated by scripts/agent-team/install-exports.mjs from .agent-team/team.json; do not edit) >>>";
export const CODEX_END = "# <<< agent-team roles <<<";

/** The generated [agents.<id>] registration block, delimited so the rest of the file is preserved. */
export function codexConfigText(manifest) {
  const blocks = manifest.roles.map((r) => `[agents.${r.id}]\ndescription = ${JSON.stringify(r.description)}\nconfig_file = "agents/${r.id}.toml"\n`);
  return `${CODEX_BEGIN}\n# Codex reads this project config only after you trust the project in Codex.\n\n${blocks.join("\n")}${CODEX_END}\n`;
}

/**
 * Merge the generated block into an existing .codex/config.toml, keeping every
 * line outside the markers (native settings the operator added). A new file
 * gets just the block.
 */
export function mergeCodexConfig(existing, block) {
  if (existing === undefined || existing === "") return block;
  const b = existing.indexOf(CODEX_BEGIN);
  const e = existing.indexOf(CODEX_END);
  if (b < 0 && e < 0) return `${existing.endsWith("\n") ? existing : `${existing}\n`}\n${block}`;
  if (b < 0 || e < b) throw new Error(".codex/config.toml has a damaged agent-team block (unmatched markers); fix it by hand");
  const after = existing.slice(e + CODEX_END.length).replace(/^\n/, "");
  return `${existing.slice(0, b)}${block}${after}`;
}
const ID = /^[a-z0-9][a-z0-9-]*$/;

// Byte-exact: .gitattributes forces LF on every generated path, so any difference is drift.
const sameBytes = (a, b) => Buffer.compare(a, b) === 0;
const markerText = (ids) => `${JSON.stringify({ generatedBy: "scripts/agent-team/install-exports.mjs", roles: ids }, null, 2)}\n`;

function previousRoles(root, target) {
  const f = path.join(root, TARGETS[target].dir, MARKER);
  return existsSync(f) ? JSON.parse(readFileSync(f, "utf8")).roles : [];
}

/**
 * Refuse to write through a symlink: the installed path must be absent or a
 * regular file, and its nearest existing directory must resolve inside root.
 */
export function assertInsideRoot(root, file) {
  if (existsSync(file) || isDanglingLink(file)) {
    if (!lstatSync(file).isFile()) throw new Error(`refusing to overwrite non-regular file ${path.relative(root, file)} (symlink or special file)`);
  }
  let dir = path.dirname(file);
  while (!existsSync(dir)) dir = path.dirname(dir);
  const realRoot = realpathSync(root);
  const realDir = realpathSync(dir);
  if (realDir !== realRoot && !realDir.startsWith(realRoot + path.sep)) throw new Error(`refusing to write ${path.relative(root, file)}: its directory resolves outside the repository`);
}

function isDanglingLink(file) {
  try {
    return lstatSync(file).isSymbolicLink();
  } catch {
    return false;
  }
}

/**
 * Plan the install of one target: which files to write, which stale roles to
 * remove, and whether the marker changes. Pure apart from reads; used by both
 * install and --check.
 */
export function planTarget(root, target, ids, exportDir) {
  const spec = TARGETS[target];
  for (const id of ids) if (!ID.test(id)) throw new Error(`refusing unsafe role id "${id}"`);
  const writes = [];
  for (const id of ids) {
    const from = path.join(exportDir, spec.exported(id));
    if (!existsSync(from) && !isDanglingLink(from)) throw new Error(`${target}: export has no file for ${id} (${spec.exported(id)})`);
    if (!lstatSync(from).isFile()) throw new Error(`${target}: refusing non-regular export file for ${id} (symlink or special file)`);
    const to = path.join(root, spec.installed(id));
    assertInsideRoot(root, to);
    const want = readFileSync(from);
    const same = existsSync(to) && sameBytes(readFileSync(to), want);
    if (!same) writes.push({ id, from, to, why: existsSync(to) ? "content differs" : "missing" });
  }
  const stale = previousRoles(root, target).filter((id) => !ids.includes(id) && ID.test(id));
  const marker = path.join(root, spec.dir, MARKER);
  assertInsideRoot(root, marker);
  const markerStale = !existsSync(marker) || !sameBytes(readFileSync(marker), Buffer.from(markerText(ids)));
  return { writes, stale, markerStale, marker };
}

function removeRole(root, target, id) {
  const p = path.join(root, TARGETS[target].installed(id));
  // MiniMax roles are directories (agents/<id>/agent.md); remove the directory.
  rmSync(target === "minimax" ? path.dirname(p) : p, { recursive: true, force: true });
}

export function applyPlan(root, target, ids, plan) {
  for (const w of plan.writes) {
    mkdirSync(path.dirname(w.to), { recursive: true });
    copyFileSync(w.from, w.to);
  }
  for (const id of plan.stale) removeRole(root, target, id);
  if (plan.markerStale) {
    mkdirSync(path.dirname(plan.marker), { recursive: true });
    writeFileSync(plan.marker, markerText(ids));
  }
}

function exportAll(manifest, tmp) {
  const cli = creatorCli();
  if (cli === undefined) throw new Error("agent-team-creator not found: set AGENT_TEAM_CREATOR to the skill directory");
  const dirs = {};
  for (const target of Object.keys(TARGETS)) {
    const input = path.join(tmp, `${target}-request.json`);
    const out = path.join(tmp, target);
    writeFileSync(input, JSON.stringify({ team: manifest, target, out }));
    const r = spawnSync(process.execPath, [cli, "export", "--input", input], { encoding: "utf8", windowsHide: true });
    if (r.status !== 0) throw new Error(`export ${target} failed: ${(r.stderr || r.stdout).trim().slice(0, 500)}`);
    dirs[target] = out;
  }
  return dirs;
}

function main() {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
  const check = process.argv.includes("--check");
  const manifest = JSON.parse(readFileSync(path.join(root, ".agent-team", "team.json"), "utf8"));
  const ids = manifest.roles.map((r) => r.id);
  const tmp = mkdtempSync(path.join(os.tmpdir(), "team-export-"));
  let drift = 0;
  try {
    const dirs = exportAll(manifest, tmp);
    for (const target of Object.keys(TARGETS)) {
      const plan = planTarget(root, target, ids, dirs[target]);
      if (check) {
        for (const w of plan.writes) console.error(`install-exports: ${path.relative(root, w.to)}: ${w.why} (hand-edited or stale; regenerate)`);
        for (const id of plan.stale) console.error(`install-exports: ${TARGETS[target].installed(id)}: role no longer in the manifest`);
        if (plan.markerStale) console.error(`install-exports: ${TARGETS[target].dir}/${MARKER}: out of date`);
        drift += plan.writes.length + plan.stale.length + (plan.markerStale ? 1 : 0);
        continue;
      }
      applyPlan(root, target, ids, plan);
      console.log(`install-exports: ${target}: ${plan.writes.length} written, ${plan.stale.length} removed`);
    }
    const codexConfig = path.join(root, CODEX_CONFIG);
    assertInsideRoot(root, codexConfig);
    const current = existsSync(codexConfig) ? readFileSync(codexConfig, "utf8") : undefined;
    const wantConfig = mergeCodexConfig(current, codexConfigText(manifest));
    if (current === undefined || !sameBytes(Buffer.from(current), Buffer.from(wantConfig))) {
      if (check) {
        console.error(`install-exports: ${CODEX_CONFIG}: out of date`);
        drift++;
      } else writeFileSync(codexConfig, wantConfig);
    }
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
  if (check && drift > 0) {
    console.error(`install-exports: ${drift} drift item(s); run node scripts/agent-team/install-exports.mjs`);
    process.exit(1);
  }
  console.log(`install-exports: ${check ? "in sync" : "done"} (${ids.length} roles x ${Object.keys(TARGETS).length} harnesses)`);
}

if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
